'use client';
import { useEffect, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowRight, Plus, Trash2 } from 'lucide-react';
import { db } from '@/lib/supabase';
import { errorText, run, useTable } from '@/lib/use-data';
import { Empty, Go, Loading, Modal, Notice, PageHead, Shell, useAuth } from './core';

type Contact={id:string;name:string;category:string;status:string;user_id:string};
type Relationship={id:string;mentor_id:string;disciple_id:string|null;contact_id:string|null;started_at:string;status:string;next_meeting:string|null};
type Group={id:string;name:string;owner_id:string;path_id:string|null};
type Meeting={id:string;group_id:string;starts_at:string;leader_id:string;path_id:string|null};
type Invitation={id:string;group_id:string;invitee_email:string;token:string;status:string};
const CATEGORIES=['семья','друзья','работа','соседи','знакомые'];
const CONTACT_STATUSES=['молюсь','открыт','общаемся о вере','читаем Писание','ученические отношения'];

export function PeoplePage(){
  const {user}=useAuth();const {data,loading,error,reload}=useTable<Contact>('contacts','user_id',user?.id,'name');
  const [editing,setEditing]=useState<Contact|null|undefined>();const [name,setName]=useState('');const [category,setCategory]=useState('друзья');const [status,setStatus]=useState('молюсь');const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');
  function open(c:Contact|null){setEditing(c);setName(c?.name||'');setCategory(c?.category||'друзья');setStatus(c?.status||'молюсь');setMsg('')}
  async function submit(e:FormEvent){e.preventDefault();if(!user)return;setBusy(true);setMsg('');try{if(editing)await run(db().from('contacts').update({name:name.trim(),category,status}).eq('id',editing.id));else await run(db().from('contacts').insert({user_id:user.id,name:name.trim(),category,status}));setEditing(undefined);await reload()}catch(e){setMsg(errorText(e))}finally{setBusy(false)}}
  async function remove(c:Contact){if(!confirm(`Удалить «${c.name}» из списка?`))return;try{await run(db().from('contacts').delete().eq('id',c.id));await reload()}catch(e){setMsg(errorText(e))}}
  return <Shell title="Люди"><div className="page"><PageHead eyebrow="ЛЮДИ РЯДОМ" title="У каждого есть имя." description="Это твой личный список. Контакт не означает, что человек зарегистрирован на платформе." action={<button className="btn" onClick={()=>open(null)}><Plus size={16}/> Добавить человека</button>}/>{msg&&<Notice error={msg}/>}
    {loading?<Loading/>:error?<Notice error={error} onRetry={reload}/>:data.length?<div className="card table-wrap"><table className="data-table"><thead><tr><th>Имя</th><th>Окружение</th><th>Статус</th><th>Действия</th></tr></thead><tbody>{data.map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.category}</td><td><span className="badge">{c.status}</span></td><td><div className="row-actions"><button className="btn small soft" onClick={()=>open(c)}>Изменить</button><button className="btn small danger" onClick={()=>remove(c)} aria-label={`Удалить ${c.name}`}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div>:<Empty title="Список пока пуст" description="Вспомни одного человека, с кем хочешь пройти часть этого пути." action={<button className="btn" onClick={()=>open(null)}>Добавить человека</button>}/>}
    {editing!==undefined&&<Modal title={editing?'Изменить человека':'Новый человек'} onClose={()=>setEditing(undefined)}><form onSubmit={submit}><div className="formrow"><label><span className="label">Имя</span><input className="field" required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label><span className="label">Окружение</span><select className="field" value={category} onChange={e=>setCategory(e.target.value)}>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="label">Статус общения</span><select className="field" value={status} onChange={e=>setStatus(e.target.value)}>{CONTACT_STATUSES.map(x=><option key={x}>{x}</option>)}</select></label></div>{msg&&<Notice error={msg}/>}<div className="modal-footer"><button type="button" className="btn soft" onClick={()=>setEditing(undefined)}>Отмена</button><button disabled={busy||!name.trim()} className="btn">Сохранить</button></div></form></Modal>}
  </div></Shell>;
}
export function RelationshipsPage(){
  const {user}=useAuth();const {data,loading,error,reload}=useTable<Relationship>('disciple_relationships','mentor_id',user?.id);
  const contacts=useTable<Contact>('contacts','user_id',user?.id,'name');const [selected,setSelected]=useState('');const [date,setDate]=useState('');const [email,setEmail]=useState('');const [modal,setModal]=useState<'local'|'invite'|null>(null);const [msg,setMsg]=useState('');const [success,setSuccess]=useState('');
  const [incoming,setIncoming]=useState<Relationship[]>([]);
  async function reloadIncoming(){if(!user)return;const r=await db().from('disciple_relationships').select('*').eq('disciple_id',user.id);if(r.error)setMsg(r.error.message);else setIncoming(r.data||[])}
  useEffect(()=>{void reloadIncoming()},[user]);
  async function addLocal(e:FormEvent){e.preventDefault();if(!user)return;setMsg('');try{await run(db().from('disciple_relationships').insert({mentor_id:user.id,contact_id:selected,status:'личная запись',next_meeting:date||null}));setModal(null);setSelected('');await reload()}catch(e){setMsg(errorText(e))}}
  async function invite(e:FormEvent){e.preventDefault();setMsg('');try{const found=await run(db().rpc('invite_disciple',{invitee_email:email.trim()}));if(!found){setMsg('Аккаунт с таким email не найден. Попросите человека зарегистрироваться, затем повторите запрос.');return}setSuccess(`Запрос для ${email} создан. Автоматическое письмо не отправляется; связь появится только после согласия человека.`);setModal(null);setEmail('');await reload()}catch(e){setMsg(errorText(e))}}
  async function respond(id:string,accept:boolean){setMsg('');try{await run(db().rpc('respond_disciple_relationship',{relationship_id:id,accept}));await reloadIncoming()}catch(e){setMsg(errorText(e))}}
  async function end(id:string){if(!confirm('Завершить эту связь ученичества?'))return;try{await run(db().rpc('leave_disciple_relationship',{relationship_id:id}));await reload();await reloadIncoming()}catch(e){setMsg(errorText(e))}}
  async function meeting(id:string,value:string){try{await run(db().from('disciple_relationships').update({next_meeting:value||null}).eq('id',id));await reload()}catch(e){setMsg(errorText(e))}}
  const contactName=(id:string|null)=>contacts.data.find(c=>c.id===id)?.name||'Человек';
  return <Shell title="Наставничество"><div className="page"><PageHead eyebrow="СЛЕДОВАТЬ ВМЕСТЕ" title="Рядом — не случайно." description="Личная запись о человеке без аккаунта и подтверждённые отношения между пользователями — разные вещи." action={<div className="row-actions"><button className="btn soft" onClick={()=>setModal('local')}>Личная запись</button><button className="btn" onClick={()=>setModal('invite')}>Запрос по email</button></div>}/>{msg&&<Notice error={msg}/>} {success&&<div className="success">{success}</div>}
  {incoming.filter(x=>x.status==='ожидает подтверждения').length>0&&<div className="card" style={{marginBottom:20}}><h3>Запросы на наставничество</h3>{incoming.filter(x=>x.status==='ожидает подтверждения').map(x=><div className="item" key={x.id}><span>Запрос от другого участника · {x.started_at}</span><div className="row-actions"><button className="btn small" onClick={()=>respond(x.id,true)}>Принять</button><button className="btn small soft" onClick={()=>respond(x.id,false)}>Отклонить</button></div></div>)}</div>}
  {loading||contacts.loading?<Loading/>:error||contacts.error?<Notice error={error||contacts.error} onRetry={reload}/>:data.length?<div className="card"><h3>Люди, которых ты сопровождаешь</h3>{data.map(r=><div className="item" key={r.id}><div><div className="item-title">{r.contact_id?contactName(r.contact_id):'Зарегистрированный участник'}</div><div className="item-meta">{r.contact_id?'Личная запись · без аккаунта':'Связь с аккаунтом'} · с {r.started_at}</div>{r.contact_id&&r.status==='личная запись'&&<label className="label" style={{marginTop:10}}>Следующая встреча<input type="date" className="field" style={{marginTop:5,maxWidth:190}} defaultValue={r.next_meeting||''} onBlur={e=>{if(e.target.value!==(r.next_meeting||''))meeting(r.id,e.target.value)}}/></label>}</div><div className="row-actions"><span className={'badge '+(r.status==='подтверждено'?'active':'')}>{r.status}</span>{r.status!=='завершено'&&<button className="btn small soft" onClick={()=>end(r.id)}>Завершить</button>}</div></div>)}</div>:<Empty title="Пока нет связей" description="Начни с человека из своего списка или создай запрос участнику. Подтверждение нельзя сделать за другого." action={<Go href="/people">Мои люди</Go>}/>}
  {incoming.filter(x=>x.status==='подтверждено').length>0&&<div className="card" style={{marginTop:20}}><h3>Мой наставник</h3>{incoming.filter(x=>x.status==='подтверждено').map(x=><div className="item" key={x.id}><span>Подтверждённая связь · {x.started_at}</span><button className="btn small soft" onClick={()=>end(x.id)}>Завершить</button></div>)}</div>}
  {modal&&<Modal title={modal==='local'?'Личное сопровождение':'Создать запрос ученику'} onClose={()=>setModal(null)}>{modal==='local'?<form onSubmit={addLocal}><p className="muted" style={{fontSize:13}}>Личная запись не создаёт аккаунт и не утверждает подтверждённую связь.</p><div className="formrow"><label><span className="label">Человек</span><select className="field" required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Выберите из списка</option>{contacts.data.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span className="label">Следующая встреча</span><input className="field" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div>{!contacts.data.length&&<Go href="/people">Добавить человека</Go>}<div className="modal-footer"><button className="btn" disabled={!selected}>Сохранить запись</button></div></form>:<form onSubmit={invite}><p className="muted" style={{fontSize:13}}>Человек должен уже иметь аккаунт. Запрос появится у него в разделе наставничества; email автоматически не отправляется.</p><label><span className="label">Электронная почта</span><input type="email" required className="field" value={email} onChange={e=>setEmail(e.target.value)}/></label><div className="modal-footer"><button className="btn">Создать запрос</button></div></form>}{msg&&<Notice error={msg}/>}</Modal>}
  </div></Shell>;
}
export function GenerationsPage(){
  const {user}=useAuth();const {data,loading,error,reload}=useTable<Relationship>('disciple_relationships','mentor_id',user?.id);
  const contacts=useTable<Contact>('contacts','user_id',user?.id);
  const [generations,setGenerations]=useState<{generation:number;people:number}[]>([]);const [genError,setGenError]=useState('');
  useEffect(()=>{if(!user)return;db().rpc('my_generations').then(r=>{if(r.error)setGenError(r.error.message);else setGenerations(r.data||[])})},[user]);
  const confirmed=data.filter(r=>r.status==='подтверждено');const personal=data.filter(r=>r.status==='личная запись');
  return <Shell title="Поколения"><div className="page"><PageHead eyebrow="УМНОЖЕНИЕ" title="Путь не заканчивается на тебе." description="Подсчёт поколений включает только подтверждённые отношения зарегистрированных людей. Личные записи показаны отдельно." />{genError&&<Notice error={genError}/>}
  {loading||contacts.loading?<Loading/>:error||contacts.error?<Notice error={error||contacts.error} onRetry={reload}/>:<div className="grid-main"><div className="stack"><div className="card"><span className="eyebrow" style={{color:'#997b41'}}>ПОДТВЕРЖДЁННЫЕ ПОКОЛЕНИЯ</span>{generations.length?<div className="stat-row" style={{marginTop:22}}>{generations.map(g=><div className="stat" key={g.generation}><strong>{g.people}</strong><span>ПОКОЛЕНИЕ {g.generation}</span></div>)}</div>:<Empty title="Пока нет подтверждённых поколений" description="Связь появится здесь после согласия человека." action={<Go href="/relationships">Наставничество</Go>}/>}<h3>Первое поколение</h3>{confirmed.map(r=><div className="item" key={r.id}><span className="item-title">Участник платформы · с {r.started_at}</span><span className="badge active">подтверждено</span></div>)}</div>{personal.length>0&&<div className="card"><h3>Личные записи вне схемы поколений</h3>{personal.map(r=><div className="item" key={r.id}><span>{contacts.data.find(c=>c.id===r.contact_id)?.name||'Человек'}</span><span className="badge">личная запись</span></div>)}</div>}</div><div className="card" style={{background:'#e9e7dc',alignSelf:'start'}}><span className="eyebrow" style={{color:'#967b43'}}>ПОЧЕМУ ЭТО ВАЖНО</span><h3 style={{fontSize:26,margin:'22px 0'}}>Не схема. Люди.</h3><p style={{lineHeight:1.75,fontSize:13,color:'#626c60'}}>Умножение начинается, когда человек слышит Христа, исполняет Его слова и сопровождает другого. Подтверждение каждого участника важно.</p></div></div>}</div></Shell>;
}
export function GroupsPage(){
  const {user}=useAuth();const router=useRouter();
  const [groups,setGroups]=useState<Group[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [name,setName]=useState('');const [open,setOpen]=useState(false);const [token,setToken]=useState('');const [busy,setBusy]=useState(false);const [success,setSuccess]=useState('');
  async function reload(){if(!user)return;setLoading(true);const memberships=await db().from('group_members').select('group_id').eq('user_id',user.id);if(memberships.error){setError(memberships.error.message);setLoading(false);return}const ids=(memberships.data||[]).map(m=>m.group_id);if(!ids.length){setGroups([]);setLoading(false);return}const result=await db().from('groups').select('*').in('id',ids).order('created_at',{ascending:false});if(result.error)setError(result.error.message);else setGroups(result.data||[]);setLoading(false)}
  useEffect(()=>{const invited=new URLSearchParams(window.location.search).get('invite');if(invited)setToken(invited)},[]);
  useEffect(()=>{void reload()},[user]);
  async function create(e:FormEvent){e.preventDefault();if(!user)return;setError('');setBusy(true);try{await run(db().from('groups').insert({owner_id:user.id,name:name.trim()}).select().single());setOpen(false);setName('');await reload()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  async function join(e:FormEvent){e.preventDefault();setError('');setBusy(true);try{const groupId=await run(db().rpc('accept_group_invitation',{invitation_token:token.trim()}));setSuccess('Приглашение принято. Вы стали участником группы.');setToken('');await reload();router.push('/groups/'+groupId)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  return <Shell title="Группы"><div className="page"><PageHead eyebrow="ВМЕСТЕ ПО ПУТИ" title="Группа — место движения." description="Встречайтесь, слушайте Слово и помогайте друг другу исполнить услышанное." action={<button className="btn" onClick={()=>setOpen(true)}><Plus size={16}/> Создать группу</button>}/>{error&&<Notice error={error} onRetry={reload}/>} {success&&<div className="success">{success}</div>}
  <div className="grid-main"><div>{loading?<Loading/>:groups.length?<div className="stack">{groups.map(g=><Link href={'/groups/'+g.id} className="card" key={g.id} style={{display:'block'}}><div className="section-row"><div><span className="eyebrow" style={{color:'#987c46'}}>{g.owner_id===user?.id?'ТВОЯ ГРУППА':'УЧАСТВУЕШЬ'}</span><h3 style={{fontSize:25,margin:'9px 0'}}>{g.name}</h3><p className="muted" style={{fontSize:12,margin:0}}>Открыть встречи и участников</p></div><ArrowRight size={21}/></div></Link>)}</div>:<Empty title="Пока нет групп" description="Создай свою группу или присоединись по приглашению." action={<button className="btn" onClick={()=>setOpen(true)}>Создать группу</button>}/>}</div><div className="card" style={{alignSelf:'start'}}><h3>Есть приглашение?</h3><p className="muted" style={{fontSize:13,lineHeight:1.6}}>Вставь токен из ссылки. Приглашение примет только аккаунт с указанным в нём email.</p><form onSubmit={join}><label className="label">ТОКЕН ПРИГЛАШЕНИЯ<input className="field" style={{marginTop:8}} required value={token} onChange={e=>setToken(e.target.value)} placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"/></label><button disabled={busy} className="btn" style={{marginTop:16}}>Присоединиться</button></form></div></div>
  {open&&<Modal title="Новая группа" onClose={()=>setOpen(false)}><form onSubmit={create}><label><span className="label">Название группы</span><input className="field" value={name} onChange={e=>setName(e.target.value)} required maxLength={100} placeholder="Например: Группа по средам"/></label><div className="modal-footer"><button className="btn" disabled={busy||!name.trim()}>{busy?'Создаём…':'Создать группу'}</button></div></form></Modal>}</div></Shell>;
}
export function GroupDetail({id}:{id:string}){
  const {user}=useAuth();const router=useRouter();const [group,setGroup]=useState<Group|null>(null);const [members,setMembers]=useState<{user_id:string;role:string}[]>([]);const [meetings,setMeetings]=useState<Meeting[]>([]);const [invitations,setInvitations]=useState<Invitation[]>([]);const [paths,setPaths]=useState<{id:string;title:string}[]>([]);const [name,setName]=useState('');const [email,setEmail]=useState('');const [date,setDate]=useState('');const [path,setPath]=useState('');const [modal,setModal]=useState<'invite'|'meeting'|'edit'|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
  async function reload(){if(!user)return;setError('');const [g,m,mt,i,p]=await Promise.all([db().from('groups').select('*').eq('id',id).maybeSingle(),db().from('group_members').select('*').eq('group_id',id),db().from('meetings').select('*').eq('group_id',id).order('starts_at',{ascending:false}),db().from('group_invitations').select('*').eq('group_id',id),db().from('gbo_paths').select('*')]);const fail=[g,m,mt,i,p].find(x=>x.error);if(fail?.error)setError(fail.error.message);else{setGroup(g.data as Group);setMembers(m.data||[]);setMeetings(mt.data||[]);setInvitations(i.data||[]);setPaths(p.data||[])}setLoading(false)}
  useEffect(()=>{void reload()},[id,user]);
  const leader=members.some(m=>m.user_id===user?.id&&m.role==='ведущий');const allowed=members.some(m=>m.user_id===user?.id);
  async function mutate(e:FormEvent){e.preventDefault();setError('');try{if(modal==='invite'){await run(db().from('group_invitations').insert({group_id:id,inviter_id:user!.id,invitee_email:email.trim(),status:'ожидает'}));setEmail('')}if(modal==='meeting'){await run(db().from('meetings').insert({group_id:id,leader_id:user!.id,starts_at:new Date(date).toISOString(),path_id:path||null}));setDate('')}if(modal==='edit'){await run(db().from('groups').update({name:name.trim()}).eq('id',id))}setModal(null);await reload()}catch(e){setError(errorText(e))}}
  async function cancelInvitation(inviteId:string){if(!confirm('Отменить приглашение?'))return;try{await run(db().from('group_invitations').update({status:'отменено'}).eq('id',inviteId));await reload()}catch(e){setError(errorText(e))}}
  async function deleteGroup(){if(!confirm('Удалить группу без возможности восстановления?'))return;try{await run(db().from('groups').delete().eq('id',id));router.push('/groups')}catch(e){setError(errorText(e))}}
  return <Shell title="Группа"><div className="page">{loading?<Loading/>:error&&!group?<Notice error={error} onRetry={reload}/>:!group?<Empty title="Группа не найдена" description="Проверь ссылку или вернись к своим группам." action={<Go href="/groups">Все группы</Go>}/>:!allowed?<Empty title="Доступ закрыт" description="Только участники видят встречи. Попроси ведущего поделиться ссылкой." action={<Go href="/groups">Мои группы</Go>}/>:<><PageHead eyebrow="ВМЕСТЕ ПО ПУТИ" title={group.name} description="Встречи, участники и общий путь." action={leader&&<div className="row-actions">{group.owner_id===user?.id&&<button className="btn soft" onClick={()=>{setName(group.name);setModal('edit')}}>Изменить</button>}<button className="btn" onClick={()=>setModal('invite')}>Создать приглашение</button></div>}/>{error&&<Notice error={error}/>}<div className="grid-main"><div className="stack"><div className="card"><div className="section-row"><h3>Встречи</h3>{leader&&<button className="btn small" onClick={()=>setModal('meeting')}><Plus size={14}/> Назначить встречу</button>}</div>{meetings.length?meetings.map(m=><div className="item" key={m.id}><div><div className="item-title">{new Date(m.starts_at).toLocaleString('ru-RU',{dateStyle:'medium',timeStyle:'short'})}</div><div className="item-meta">{paths.find(p=>p.id===m.path_id)?.title||'Путь пока не выбран'}</div></div><Go href={'/gbo/'+m.id} variant="small soft">Открыть ГБО</Go></div>):<Empty title="Встреч пока нет" description="Назначь первую встречу, чтобы пройти путь вместе."/>}</div><div className="card"><h3>Участники</h3>{members.map((m,i)=><div className="item" key={i}><span className="item-title">{m.user_id===user?.id?'Вы':m.user_id.slice(0,8)+'…'}</span><span className="badge">{m.role}</span></div>)}</div></div><div className="stack"><div className="card"><span className="eyebrow" style={{color:'#967b43'}}>НАШ ПУТЬ</span><h3 style={{margin:'19px 0'}}>Быть рядом и идти глубже.</h3><p className="muted" style={{fontSize:13,lineHeight:1.7}}>На каждой встрече: забота друг о друге, Слово и конкретный шаг послушания.</p></div>{leader&&<div className="card"><h3>Приглашения</h3>{invitations.map(i=><div className="item" key={i.id} style={{display:'block'}}><div className="item-title">{i.invitee_email}</div><div className="item-meta">{i.status}</div>{i.status==='ожидает'&&<div className="row-actions" style={{marginTop:10}}><button className="link-button" onClick={()=>navigator.clipboard.writeText(window.location.origin+'/groups?invite='+i.token).then(()=>alert('Ссылка скопирована. Передайте её участнику сами.')).catch(e=>setError(errorText(e)))}>Скопировать ссылку</button><button className="btn small soft" onClick={()=>cancelInvitation(i.id)}>Отменить</button></div>}</div>)}{!invitations.length&&<p className="muted">Приглашений пока нет.</p>}{group.owner_id===user?.id&&<button className="btn small soft" onClick={deleteGroup} style={{marginTop:20}}>Удалить группу</button>}</div>}</div></div></>}
  {modal&&<Modal title={modal==='invite'?'Создать ссылку приглашения':modal==='meeting'?'Новая встреча':'Название группы'} onClose={()=>setModal(null)}><form onSubmit={mutate}>{modal==='invite'?<><p className="muted" style={{fontSize:13}}>Скопируйте ссылку после создания и отправьте человеку сами. Письмо автоматически не отправляется.</p><label><span className="label">Email участника</span><input className="field" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label></>:modal==='meeting'?<div className="formrow"><label><span className="label">Дата и время</span><input className="field" type="datetime-local" required value={date} onChange={e=>setDate(e.target.value)}/></label><label><span className="label">Путь ГБО</span><select className="field" value={path} onChange={e=>setPath(e.target.value)}><option value="">Путь не выбран</option>{paths.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label></div>:<label><span className="label">Название</span><input className="field" required value={name} onChange={e=>setName(e.target.value)}/></label>}{error&&<Notice error={error}/>}<div className="modal-footer"><button className="btn">Сохранить</button></div></form></Modal>}</div></Shell>;
}