'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, ChevronLeft, ChevronRight, LockKeyhole } from 'lucide-react';
import { db } from '@/lib/supabase';
import { errorText, run } from '@/lib/use-data';
import { Empty, Go, Loading, Notice, PageHead, Shell, useAuth } from './core';

export const MODULE_TITLES=['Кто такой ученик?','Цена следования','Евангелие Царства','Слово и послушание','Молитва и пребывание','Моя история','Моё окружение','Делай учеников','Духовная семья','Лидер, который снаряжает','Поколения учеников','Иди и умножай'];
const STAGES=['НАЗАД','СЛОВО','ВИДЕО','ОТКРОЙ','ПРАКТИКА','ПОСЛУШАНИЕ','ПЕРЕДАЧА','МОЛИТВА','ВПЕРЁД'];
const RESULTS=['запланировано','сделал','пока нет','нужна помощь'] as const;
type Module={id:number;title:string;position:number;published:boolean};
type Lesson={id:string;module_id:number;title:string;status:string;version:number};
type Block={id:string;kind:string;position:number;content:Record<string,any>};
type Contact={id:string;name:string;user_id:string};
type Action={id:string;decision:string;due_date:string;contact_id:string|null;status:string;result_note:string;transferred:boolean};
export function SchoolPage(){
  const {user}=useAuth();const [modules,setModules]=useState<Module[]>([]);const [lesson,setLesson]=useState<Lesson|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  useEffect(()=>{if(!user)return;Promise.all([db().from('modules').select('*').order('position'),db().from('lessons').select('*').eq('module_id',1).eq('status','published').limit(1)]).then(([m,l])=>{if(m.error)throw m.error;if(l.error)throw l.error;setModules(m.data as Module[]);setLesson((l.data?.[0] as Lesson)||null)}).catch(e=>setError(errorText(e))).finally(()=>setLoading(false))},[user]);
  return <Shell title="Школа"><div className="page"><PageHead eyebrow="01 / ШКОЛА УЧЕНИЧЕСТВА" title="Учиться следовать." description="12 тем о жизни с Иисусом. Начни с первого модуля — остальные появятся после публикации."/><div className="module-list">{loading?<Loading/>:error?<Notice error={error} onRetry={()=>location.reload()}/>:MODULE_TITLES.map((fallback,i)=>{const m=modules.find(x=>x.position===i+1||x.id===i+1);return <div className="module" key={i}><span className="module-number">{String(i+1).padStart(2,'0')}</span><div><h3>{m?.title||fallback}</h3><p>{i===0?'Первый шаг начинается здесь':'Материалы готовятся к публикации'}</p></div>{i===0?(lesson?<Go href="/lesson/1" variant="gold">Открыть урок</Go>:<span className="badge">Ожидает публикации</span>):<span className="badge"><LockKeyhole size={12} style={{marginRight:5}}/> Скоро</span>}</div>})}</div></div></Shell>;
}
export function DashboardPage(){
  const {user}=useAuth();const [profile,setProfile]=useState('');const [lesson,setLesson]=useState<Lesson|null>(null);const [counts,setCounts]=useState([0,0,0]);const [actions,setActions]=useState<Action[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
  useEffect(()=>{if(!user)return;Promise.all([db().from('profiles').select('display_name').eq('id',user.id).maybeSingle(),db().from('contacts').select('id').eq('user_id',user.id),db().from('disciple_relationships').select('id').eq('mentor_id',user.id).neq('status','завершено'),db().from('groups').select('id').eq('owner_id',user.id),db().from('obedience_actions').select('*').eq('user_id',user.id).order('due_date',{ascending:true}),db().from('lessons').select('*').eq('module_id',1).eq('status','published').limit(1)]).then(([p,c,r,g,a,l])=>{const fail=[p,c,r,g,a,l].find(x=>x.error);if(fail?.error)throw fail.error;setProfile(p.data?.display_name||user.user_metadata?.display_name||'друг');setCounts([c.data?.length||0,r.data?.length||0,g.data?.length||0]);setActions((a.data||[]) as Action[]);setLesson((l.data?.[0] as Lesson)||null)}).catch(e=>setError(errorText(e))).finally(()=>setLoading(false))},[user]);
  return <Shell title="Сегодня"><div className="page"><PageHead eyebrow="ТВОЙ ПУТЬ" title={`Мир тебе, ${profile||'друг'}.`} description="Не нужно пройти всё за день. Выбери один верный шаг и сделай его." />{loading?<Loading/>:<>{error&&<Notice error={error} onRetry={()=>location.reload()}/>}<div className="stat-row"><div className="stat"><strong>{counts[0]}</strong><span>ЛЮДЕЙ РЯДОМ</span></div><div className="stat"><strong>{counts[1]}</strong><span>СВЯЗЕЙ УЧЕНИЧЕСТВА</span></div><div className="stat"><strong>{counts[2]}</strong><span>ТВОИХ ГРУПП</span></div></div><div className="grid-main"><div className="stack"><div className="feature"><span className="eyebrow goldtext">ПРОДОЛЖИ ПУТЬ · УРОК 01</span><h2>Быть учеником — значит следовать.</h2><p>Первый урок помогает перейти от слушания к конкретному действию.</p>{lesson?<Go href="/lesson/1" variant="gold">Перейти к уроку</Go>:<Go href="/school" variant="gold">Открыть школу</Go>}</div><div className="card"><div className="section-row"><h3>Твои решения</h3>{lesson&&<Link href="/lesson/1" className="link-button">К уроку →</Link>}</div>{actions.length?actions.slice(0,4).map(a=><div className="item" key={a.id}><div><div className="item-title">{a.decision}</div><div className="item-meta">До {a.due_date}</div></div><span className={'badge '+(a.status==='сделал'?'active':'gold')}>{a.status}</span></div>):<Empty title="Пока нет решений" description="Пройди первый урок и запиши шаг, который сделаешь."/ >}</div></div><div className="stack"><div className="card"><span className="eyebrow" style={{color:'#997a40'}}>ФОКУС НА СЕГОДНЯ</span><h3 style={{fontSize:26,margin:'28px 0 15px'}}>Один человек. Один разговор. Один шаг.</h3><p className="muted" style={{fontSize:13,lineHeight:1.7}}>Кого ты можешь поддержать на пути веры? Запиши его имя, чтобы не забыть.</p><Go href="/people">Мои люди</Go></div><div className="card"><h3>Следующий шаг</h3><div className="timeline"><div className="timeline-row"><span className="timeline-dot"/> Открой первый урок</div><div className="timeline-row"><span className="timeline-dot"/> Запиши конкретное решение</div><div className="timeline-row"><span className="timeline-dot"/> Поделись с другим человеком</div></div></div></div></div></>}</div></Shell>;
}
export function LessonPage(){
  const {user}=useAuth();
  const [lesson,setLesson]=useState<Lesson|null>(null);const [blocks,setBlocks]=useState<Block[]>([]);const [step,setStep]=useState(0);const [answers,setAnswers]=useState<Record<string,string>>({});
  const [action,setAction]=useState<Action|null>(null);const [contacts,setContacts]=useState<Contact[]>([]);const [decision,setDecision]=useState('');const [date,setDate]=useState('');const [contactId,setContactId]=useState('');const [result,setResult]=useState('');const [outcome,setOutcome]=useState<string>('запланировано');
  const [error,setError]=useState('');const [saveState,setSaveState]=useState<'ready'|'saving'|'saved'|'error'>('ready');const [loading,setLoading]=useState(true);
  const initialized=useRef(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const lastSaved=useRef('');
  useEffect(()=>{if(!user)return;let cancelled=false;async function load(){try{
    const l=await run(db().from('lessons').select('*').eq('module_id',1).eq('status','published').limit(1));if(!l.length)throw new Error('Первый урок ещё не опубликован. Вернитесь в школу позже.');
    const current=l[0] as Lesson;const [b,p,a,c]=await Promise.all([db().from('lesson_blocks').select('*').eq('lesson_id',current.id).order('position'),db().from('lesson_progress').select('*').eq('user_id',user!.id).eq('lesson_id',current.id).maybeSingle(),db().from('obedience_actions').select('*').eq('user_id',user!.id).eq('lesson_id',current.id).order('created_at',{ascending:false}).limit(1),db().from('contacts').select('*').eq('user_id',user!.id).order('name')]);
    const fail=[b,p,a,c].find(x=>x.error);if(fail?.error)throw fail.error;if(cancelled)return;
    const savedStep=Math.max(0,Math.min(8,p.data?.step||0));const savedAnswers=p.data?.answers||{};
    setLesson(current);setBlocks(b.data||[]);setStep(savedStep);setAnswers(savedAnswers);lastSaved.current=JSON.stringify({step:savedStep,answers:savedAnswers});setSaveState('saved');
    const act=a.data?.[0] as Action|undefined;if(act){setAction(act);setDecision(act.decision);setDate(act.due_date);setContactId(act.contact_id||'');setResult(act.result_note||'');setOutcome(act.status)}
    setContacts(c.data||[]);initialized.current=true;
  }catch(e){if(!cancelled)setError(errorText(e))}finally{if(!cancelled)setLoading(false)}}
  void load();return()=>{cancelled=true};
  },[user]);
  useEffect(()=>{
    if(!initialized.current||!user||!lesson)return;
    const snapshot=JSON.stringify({step,answers});if(snapshot===lastSaved.current)return;
    setSaveState('saving');if(timer.current)clearTimeout(timer.current);
    timer.current=setTimeout(async()=>{const {error:saveError}=await db().from('lesson_progress').upsert({user_id:user.id,lesson_id:lesson.id,answers,step,updated_at:new Date().toISOString()},{onConflict:'user_id,lesson_id'});if(saveError){setError('Не удалось сохранить ответы: '+saveError.message);setSaveState('error')}else{lastSaved.current=snapshot;setSaveState('saved')}},650);
    return()=>{if(timer.current)clearTimeout(timer.current)};
  },[answers,step,user,lesson]);
  async function saveAction(){if(!user||!lesson)return;setError('');try{
    const payload={user_id:user.id,lesson_id:lesson.id,decision:decision.trim(),due_date:date,contact_id:contactId||null,status:outcome,result_note:result.trim(),transferred:action?.transferred||false};
    const saved=action?await run(db().from('obedience_actions').update(payload).eq('id',action.id).select().single()):await run(db().from('obedience_actions').insert(payload).select().single());
    setAction(saved as Action);
  }catch(e){setError(errorText(e))}}
  async function markTransfer(value:boolean){if(!action)return;setError('');try{const saved=await run(db().from('obedience_actions').update({transferred:value,contact_id:contactId||null}).eq('id',action.id).select().single());setAction(saved as Action)}catch(e){setError(errorText(e))}}
  const byKind=(kind:string)=>blocks.filter(b=>b.kind===kind);
  const renderText=(kind:string)=><>{byKind(kind).map(b=><div key={b.id} style={{margin:'22px 0'}}><h3>{b.content.heading||b.content.title}</h3><p style={{lineHeight:1.8,color:'#5e685f'}}>{b.content.body||b.content.text}</p>{b.content.source&&<a className="link-button" href={b.content.source} target="_blank" rel="noopener noreferrer">Открыть источник ↗</a>}</div>)}</>;
  return <Shell title="Первый урок"><div className="page"><PageHead eyebrow="ШКОЛА / МОДУЛЬ 01" title={lesson?.title||'Первый урок'} description="Услышь Слово, ответь и сделай конкретный шаг." action={<Go href="/school" variant="soft">Все модули</Go>}/>{loading?<Loading/>:error&&!lesson?<Notice error={error} onRetry={()=>location.reload()}/>:<><div className="progress-steps">{STAGES.map((_,i)=><span key={i} className={i<=step?'done':''}/>)}</div><div className="lesson-layout"><div className="card lesson-panel"><span className="eyebrow" style={{color:'#a78b50'}}>ШАГ {step+1} / {STAGES.length}</span><h2 style={{marginTop:16}}>{STAGES[step]}</h2>
  {step===0&&<><p className="muted">Оглянись: что ты уже знаешь об ученичестве? С каким вопросом пришёл сегодня?</p>{renderText('text')}<label><span className="label">Мой вопрос перед началом</span><textarea className="field" value={answers.before||''} onChange={e=>setAnswers({...answers,before:e.target.value})} placeholder="Запиши то, что важно для тебя…"/></label></>}
  {step===1&&<><p className="muted">Прочитай текст в Синодальном переводе. Ссылка ведёт к источнику каждого отрывка.</p>{byKind('scripture').length?byKind('scripture').map(b=><div className="verse" key={b.id}><div>{b.content.text}</div><div style={{fontSize:12,marginTop:12,color:'#756d58'}}>{b.content.reference} · {b.content.translation} {b.content.source&&<a href={b.content.source} target="_blank" rel="noopener noreferrer" className="link-button">Открыть текст ↗</a>}</div></div>):<Notice error="Тексты Писания ещё не добавлены редактором. Урок не содержит цитат для этого шага."/>}{renderText('quote')}</>}
  {step===2&&<>{byKind('video').length?byKind('video').map(b=><div key={b.id} className="card" style={{marginTop:22}}><h3>{b.content.heading||'Видеоматериал'}</h3>{b.content.url?<a className="btn" href={b.content.url} target="_blank" rel="noopener noreferrer">Открыть видео <ArrowRight size={15}/></a>:<p>{b.content.body||'Ссылка на видео не указана.'}</p>}</div>):<div className="empty"><h3>Этот урок доступен без видео</h3><p>Продолжай в тексте. Не нужно ждать записи, чтобы услышать Слово и ответить на него.</p></div>}{renderText('image')}{renderText('download')}</>}
  {step===3&&<><p className="muted">Запиши, что услышал именно ты. Ответы сохраняются в твоём профиле.</p>{renderText('reflection')}{byKind('question').length?byKind('question').map((b,i)=>{const key=b.content.key||b.id;return <div style={{margin:'27px 0'}} key={b.id}><label className="question" htmlFor={'answer-'+i}>{b.content.prompt||'Вопрос без формулировки'}</label><textarea id={'answer-'+i} className="field" value={answers[key]||''} onChange={e=>setAnswers({...answers,[key]:e.target.value})} placeholder="Запиши свои мысли…"/></div>}):<Notice error="Вопросы пока не добавлены в этот урок."/>}</>}
  {step===4&&<><p className="muted">От размышления к действию: выбери наблюдаемый шаг на эту неделю.</p>{renderText('practice')}<label><span className="label">Моя идея для конкретного шага</span><textarea className="field" value={answers.practice||''} onChange={e=>setAnswers({...answers,practice:e.target.value})} placeholder="Что я могу сделать?"/></label></>}
  {step===5&&<>{renderText('obedience_action')}<div className="formrow"><label><span className="label">Что я сделаю?</span><textarea className="field" value={decision} onChange={e=>setDecision(e.target.value)} placeholder="Одно конкретное действие"/></label><label><span className="label">До какой даты?</span><input type="date" className="field" value={date} onChange={e=>setDate(e.target.value)}/></label></div><button className="btn" disabled={!decision.trim()||!date} onClick={saveAction}>{action?'Обновить решение':'Сохранить решение'}</button>{action&&<div style={{marginTop:25,borderTop:'1px solid #dedbd0',paddingTop:20}}><h3>Вернись с результатом</h3><p className="muted" style={{fontSize:13}}>Выбери честное состояние отдельно от записи решения. Можно попросить помощи.</p><div className="row-actions" style={{marginBottom:17}}>{RESULTS.map(s=><button key={s} className={'btn small '+(outcome===s?'':'soft')} onClick={()=>setOutcome(s)}>{s}</button>)}</div><label><span className="label">Что произошло?</span><textarea className="field" value={result} onChange={e=>setResult(e.target.value)} placeholder="Опиши результат или трудность…"/></label><button className="btn small" style={{marginTop:12}} onClick={saveAction}>Сохранить результат</button><div className="success">Сохранённое состояние: {action.status}</div></div>}</>}
  {step===6&&<>{renderText('person_selector')}<label><span className="label">Кому передам услышанное?</span><select className="field" value={contactId} onChange={e=>setContactId(e.target.value)}><option value="">Пока не выбрано</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><Link href="/people" className="link-button" style={{display:'inline-block',marginTop:12}}>Добавить человека в карту окружения →</Link>{action?<div style={{marginTop:25}}><p className="muted" style={{fontSize:13}}>Отметь передачу только после реального разговора. Выбор контакта сам по себе не считается передачей.</p><button className="btn" onClick={()=>markTransfer(!action.transferred)}>{action.transferred?'Отменить отметку передачи':'Я передал это другому'}</button>{action.transferred&&<div className="success">Передача отмечена.</div>}</div>:<p className="muted" style={{marginTop:24}}>Сначала сохрани решение на шаге «Послушание», затем сможешь отметить передачу.</p>}</>}
  {step===7&&<>{renderText('prayer')}{!byKind('prayer').length&&<p className="muted">Молитвенный текст для этого урока пока не добавлен.</p>}<label><span className="label">Моя молитва (необязательно)</span><textarea className="field" value={answers.prayer||''} onChange={e=>setAnswers({...answers,prayer:e.target.value})} placeholder="Запиши своими словами…"/></label></>}
  {step===8&&<>{renderText('next_step')}<div className="card" style={{background:'#f1f0e7',margin:'24px 0'}}><span className="label">ТВОЙ СЛЕДУЮЩИЙ ШАГ</span>{action?<><strong>{action.decision}</strong><p className="muted" style={{fontSize:12,margin:'8px 0'}}>До {action.due_date} · {action.status}{action.transferred?' · передано дальше':''}</p></>:<p className="muted" style={{fontSize:13}}>Решение пока не записано. Ты можешь вернуться на шаг «Послушание».</p>}</div><Go href="/dashboard">Продолжить путь</Go></>}
  {error&&<Notice error={error}/>}<div className="lesson-actions"><button className="btn line" style={{color:'#2e3a2f'}} disabled={step===0} onClick={()=>setStep(step-1)}><ChevronLeft size={16}/> Назад</button><span role="status" style={{fontSize:11,color:saveState==='error'?'#923c32':'#697469',alignSelf:'center'}}>{saveState==='saving'?'Сохраняем…':saveState==='saved'?'Ответы сохранены':saveState==='error'?'Ошибка сохранения':'Изменения ещё не сохранены'}</span>{step<8&&<button className="btn" onClick={()=>setStep(step+1)}>Дальше <ChevronRight size={16}/></button>}</div></div><aside className="stack" style={{alignContent:'start'}}><div className="card"><span className="eyebrow" style={{color:'#a78b50'}}>СОДЕРЖАНИЕ</span><div className="timeline" style={{marginTop:18}}>{STAGES.map((s,i)=><button key={s} onClick={()=>setStep(i)} style={{display:'flex',alignItems:'center',gap:10,background:i===step?'#e9e7dc':'transparent',border:0,borderRadius:6,padding:9,textAlign:'left',fontWeight:i===step?700:500,fontSize:12}}><span className="timeline-dot"/>{String(i+1).padStart(2,'0')} / {s}</button>)}</div></div><div className="card"><h3>Жить услышанным</h3><p className="muted" style={{fontSize:13,lineHeight:1.7}}>Изучение урока — начало. Вернись к решению после выбранной даты и расскажи, что произошло на самом деле.</p></div></aside></div></>}</div></Shell>;
}